version: 2

models:
  - name: stg_asteroids_saw
    description: This model cleans up customer data

  - name: asteroid
    description: Relevant data of the asteroid

  - name: close_approach_data
    description: list of all close approaches
